In [1]:
from sklearn import datasets
boston = datasets.load_boston()

In [2]:
type(boston)

sklearn.utils.Bunch

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_boston

boston = load_boston()

dataFrame_x = pd.DataFrame(boston.data, columns = boston.feature_names)
dataFrame_y = pd.DataFrame(boston.target)

In [8]:
xdata = dataFrame_x['CHAS'][dataFrame_x['CHAS'] < 1].values
ydata = dataFrame_y[dataFrame_x['CHAS'] < 1].values.flatten()

xmesh = np.linspace(min(xdata), max(xdata), 50)

fit = np.poly1d(np.polyfit(xdata, ydata, 1))

plt.plot(xdata, ydata, 'bo', label='Data')
plt.plot(xmesh, fit(xmesh), '-r', label='Fit')
plt.legend(fontsize=16)
plt.xlabel('CHAS', fontsize=18)
plt.ylabel('Target',fontsize=18)
plt.show()

C:\Users\Ger\Ana\lib\site-packages\numpy\lib\polynomial.py:627: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale


LinAlgError: SVD did not converge in Linear Least Squares

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
from sklearn.datasets import load_boston 
from string import ascii_letters

In [5]:
from sklearn.model_selection import ShuffleSplit

In [6]:
print("Boston housing dataset has {} data points with {} variables each.".format(*df.shape))

NameError: name 'df' is not defined

In [7]:
from sklearn.datasets import load_boston

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
boston = load_boston()

In [10]:
df = pd.DataFrame(boston.data, columns = ['CHAS'])

ValueError: Shape of passed values is (13, 506), indices imply (1, 506)

In [11]:
df['target'] = boston.target

NameError: name 'df' is not defined

In [12]:
df

NameError: name 'df' is not defined

In [13]:
ax, fig = plt.subplots(figsize = (16, 10))
sns.heatmap(df.corr(), annot= True, cmap = 'RdYlGn')
plt.show()

NameError: name 'df' is not defined

In [20]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
x = df['NOX']
y = df['target']
plt.hist((x, normed=True, bins=30), (y, normed=True, bins=30))
plt.ylabel('Nitric Oxides')

SyntaxError: invalid syntax (<ipython-input-20-95e07916f357>, line 6)

In [14]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit

# Import supplementary visualizations code visuals.py


# Pretty display for notebooks
%matplotlib inline

# Load the Boston housing dataset
prices = df['target']
features = df.drop('target', axis = 1)
    
# Success
print("Boston housing dataset has {} data points with {} variables each.".format(*df.shape))

NameError: name 'df' is not defined

In [15]:
# Minimum price of the data
minimum_price = np.amin(prices)

# Maximum price of the data
maximum_price = np.amax(prices)

# Mean price of the data
mean_price = np.mean(prices)

# Median price of the data
median_price = np.median(prices)

# Standard deviation of prices of the data
std_price = np.std(prices)

# Show the calculated statistics
print("Statistics for Boston housing dataset(in thousands):\n")
print("Minimum price: ${:,.2f}".format(minimum_price)) 
print("Maximum price: ${:,.2f}".format(maximum_price))
print("Mean price: ${:,.2f}".format(mean_price))
print("Median price ${:,.2f}".format(median_price))
print("Standard deviation of prices: ${:,.2f}".format(std_price))

NameError: name 'prices' is not defined

In [31]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline# Calculate and show pairplot
sns.pairplot(df, size=2.5)
plt.tight_layout()
plt.show()

UsageError: unrecognized arguments: Calculate and show pairplot


In [40]:
x = np(boston['NOX'])

KeyError: 'NOX'

In [1]:
import keras as kr

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8

In [15]:
import pandas as pd
import numpy as np

In [16]:
from sklearn.datasets import load_boston
boston_dataset = load_boston()
df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names, delim_whitespace=True, header=None)

TypeError: __init__() got an unexpected keyword argument 'delim_whitespace'

In [17]:
df['MEDV'] = boston_dataset.target

NameError: name 'df' is not defined

In [18]:
df

NameError: name 'df' is not defined

In [19]:
inputs = df[['CHAS', 'RM', 'CRIM']]
inputs

NameError: name 'df' is not defined

In [8]:
output = df['MEDV']
output

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
5      28.7
6      22.9
7      27.1
8      16.5
9      18.9
10     15.0
11     18.9
12     21.7
13     20.4
14     18.2
15     19.9
16     23.1
17     17.5
18     20.2
19     18.2
20     13.6
21     19.6
22     15.2
23     14.5
24     15.6
25     13.9
26     16.6
27     14.8
28     18.4
29     21.0
       ... 
476    16.7
477    12.0
478    14.6
479    21.4
480    23.0
481    23.7
482    25.0
483    21.8
484    20.6
485    21.2
486    19.1
487    20.6
488    15.2
489     7.0
490     8.1
491    13.6
492    20.1
493    21.8
494    24.5
495    23.1
496    19.7
497    18.3
498    21.2
499    17.5
500    16.8
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [84]:
m = kr.models.Sequential()

#m.add(kr.layers.Dense(10, input_dim=3, activation="linear"))
#m.add(kr.layers.Dense(30, input_dim=3, activation="sigmoid"))
m.add(kr.layers.Dense(13, input_dim=3, kernel_initializer="normal", activation="relu"))
m.add(kr.layers.Dense(13, input_dim=3, kernel_initializer="normal", activation="relu"))
m.add(kr.layers.Dense(13, input_dim=3, kernel_initializer="normal", activation="relu"))
m.add(kr.layers.Dense(13, input_dim=3, kernel_initializer="normal", activation="relu"))
m.add(kr.layers.Dense(13, input_dim=3, kernel_initializer="normal", activation="relu"))

#m.compile(loss="mean_squared_error", optimizer="adam")
m.compile(loss="mean_squared_error", optimizer="adam", metrics=['accuracy'])

In [85]:
m.fit(inputs, output, epochs=100, batch_size=10, verbose=1)

ValueError: Error when checking target: expected dense_112 to have shape (13,) but got array with shape (1,)

In [53]:
m.predict(inputs)

array([[26.994118 ],
       [25.563202 ],
       [32.55387  ],
       [30.881802 ],
       [32.23323  ],
       [25.648794 ],
       [21.688358 ],
       [23.235432 ],
       [17.997017 ],
       [21.626    ],
       [25.187914 ],
       [21.66612  ],
       [20.500017 ],
       [20.977097 ],
       [22.377527 ],
       [19.871883 ],
       [20.519764 ],
       [21.26658  ],
       [16.119356 ],
       [18.784294 ],
       [16.93924  ],
       [20.976389 ],
       [22.263062 ],
       [19.424358 ],
       [20.661356 ],
       [17.481613 ],
       [19.644894 ],
       [21.662632 ],
       [26.02308  ],
       [27.412775 ],
       [18.367281 ],
       [21.486752 ],
       [20.33873  ],
       [18.238361 ],
       [21.420778 ],
       [20.918495 ],
       [20.034494 ],
       [20.117693 ],
       [21.259617 ],
       [27.18944  ],
       [31.11663  ],
       [28.83743  ],
       [23.206295 ],
       [23.609644 ],
       [22.24472  ],
       [18.49423  ],
       [19.51293  ],
       [21.87

In [54]:
output.as_matrix()

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [55]:
np.around(m.predict(inputs).T)

array([[27., 26., 33., 31., 32., 26., 22., 23., 18., 22., 25., 22., 21.,
        21., 22., 20., 21., 21., 16., 19., 17., 21., 22., 19., 21., 17.,
        20., 22., 26., 27., 18., 21., 20., 18., 21., 21., 20., 20., 21.,
        27., 31., 29., 23., 24., 22., 18., 20., 22., 16., 18., 21., 23.,
        26., 22., 20., 33., 25., 29., 23., 21., 19., 21., 26., 29., 32.,
        24., 19., 20., 18., 20., 26., 21., 22., 24., 24., 24., 24., 23.,
        24., 20., 28., 27., 24., 23., 25., 28., 22., 23., 31., 32., 26.,
        25., 26., 24., 24., 27., 23., 40., 38., 35., 28., 29., 25., 23.,
        23., 20., 20., 23., 26., 24., 23., 28., 21., 22., 24., 21., 23.,
        22., 20., 19., 20., 22., 21., 20., 20., 21., 18., 19., 26., 18.,
        26., 24., 25., 20., 19., 25., 21., 26., 20., 23., 23., 12., 21.,
        18., 12., 21., 17., 11., 13., 17., 22., 15., 16., 18., 25., 26.,
        14., 30., 21., 25., 26., 34., 38., 42., 19., 21., 36., 19., 23.,
        23., 20., 19., 17., 26., 20., 27., 22., 25.

In [56]:
m.predict(inputs).T - output.as_matrix()

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[ 2.99411774e+00,  3.96320190e+00, -2.14612885e+00,
        -2.51819839e+00, -3.96676941e+00, -3.05120583e+00,
        -1.21164169e+00, -3.86456833e+00,  1.49701691e+00,
         2.72599945e+00,  1.01879139e+01,  2.76612053e+00,
        -1.19998283e+00,  5.77096558e-01,  4.17752724e+00,
        -2.81166077e-02, -2.58023605e+00,  3.76658058e+00,
        -4.08064384e+00,  5.84294128e-01,  3.33923950e+00,
         1.37638893e+00,  7.06306152e+00,  4.92435837e+00,
         5.06135597e+00,  3.58161316e+00,  3.04489365e+00,
         6.86263199e+00,  7.62308083e+00,  6.41277504e+00,
         5.66728096e+00,  6.98675156e+00,  7.13872986e+00,
         5.13836136e+00,  7.92077827e+00,  2.01849518e+00,
         3.44944000e-02, -8.82307053e-01, -3.44038315e+00,
        -3.61056023e+00, -3.78336945e+00,  2.23742905e+00,
        -2.09370499e+00, -1.09035606e+00,  1.04472046e+00,
        -8.05769730e-01, -4.87070084e-01,  5.27973213e+00,
         1.30851803e+00, -1.68764153e+00,  1.51547127e+0

In [57]:
###difference between what the neuron is predicting and the actual values we told it to predict
np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


124.17312193026822

In [2]:
np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

NameError: name 'np' is not defined

In [17]:
from sklearn.datasets import load_boston 

In [21]:
boston_dataset = load_boston()
df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [27]:
df['MEDV'] = boston_dataset.target 

In [28]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [23]:

X = df.iloc[:,0:13].values
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [29]:
Y = df.iloc[:,13].values
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [30]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [31]:
model = Sequential()
model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model asking for accuracy, too:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

model.fit(X, Y,
     batch_size=5,
     epochs=100,
     verbose=1)

Epoch 1/100
506/506 [==============================] - 0s 508us/step - loss: 185.0876 - accuracy: 0.0099
Epoch 2/100
506/506 [==============================] - 0s 215us/step - loss: 86.6580 - accuracy: 0.0079
Epoch 3/100
506/506 [==============================] - 0s 237us/step - loss: 74.1094 - accuracy: 0.0059
Epoch 4/100
506/506 [==============================] - 0s 233us/step - loss: 68.6533 - accuracy: 0.0099
Epoch 5/100
506/506 [==============================] - 0s 245us/step - loss: 66.4283 - accuracy: 0.0099
Epoch 6/100
506/506 [==============================] - 0s 229us/step - loss: 62.5490 - accuracy: 0.0020
Epoch 7/100
506/506 [==============================] - 0s 237us/step - loss: 60.3823 - accuracy: 0.0079
Epoch 8/100
506/506 [==============================] - 0s 231us/step - loss: 58.1907 - accuracy: 0.0059
Epoch 9/100
506/506 [==============================] - 0s 235us/step - loss: 56.9308 - accuracy: 0.0020
Epoch 10/100
506/506 [==============================] - 0s 245u

506/506 [==============================] - 0s 199us/step - loss: 19.1421 - accuracy: 0.0178
Epoch 80/100
506/506 [==============================] - 0s 193us/step - loss: 20.7141 - accuracy: 0.0217
Epoch 81/100
506/506 [==============================] - 0s 192us/step - loss: 21.6180 - accuracy: 0.0099
Epoch 82/100
506/506 [==============================] - 0s 193us/step - loss: 20.6519 - accuracy: 0.0099
Epoch 83/100
506/506 [==============================] - 0s 193us/step - loss: 21.1847 - accuracy: 0.0138
Epoch 84/100
506/506 [==============================] - 0s 192us/step - loss: 21.2270 - accuracy: 0.0079
Epoch 85/100
506/506 [==============================] - 0s 192us/step - loss: 20.7400 - accuracy: 0.0119
Epoch 86/100
506/506 [==============================] - 0s 193us/step - loss: 19.2195 - accuracy: 0.0138
Epoch 87/100
506/506 [==============================] - 0s 192us/step - loss: 19.3468 - accuracy: 0.0138
Epoch 88/100
506/506 [==============================] - 0s 197us/ste

In [32]:
score = model.evaluate(X, Y, verbose=0)
score

[17.42553353592341, 0.013833992183208466]

In [33]:
def binary_accuracy(y_true, y_pred):
    return K.mean(K.equal(y_true, K.round(y_pred)), axis=-1)

In [34]:
y_pred = model.predict(X)
l = len(Y)
acc = sum([np.round(y_pred[i])==Y[i] for i in range(l)])/l
acc

array([0.01383399])

In [35]:
from matplotlib import pyplot as plt

In [36]:
plt.plot(hist.history['acc'])
plt.plot(hist.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='lower right')
plt.show()

NameError: name 'hist' is not defined

In [41]:
from keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

57344/57026 [==============================] - 0s 4us/step


In [42]:
print(f'Training data : {train_data.shape}')
print(f'Test data : {test_data.shape}')
print(f'Training sample : {train_data[0]}')
print(f'Training target sample : {train_targets[0]}')

Training data : (404, 13)
Test data : (102, 13)
Training sample : [  1.23247   0.        8.14      0.        0.538     6.142    91.7
   3.9769    4.      307.       21.      396.9      18.72   ]
Training target sample : 15.2


## Preparing the data

In [43]:
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std

## Building the network

In [44]:
from keras import models
from keras import layers

def build_model():
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu', input_shape=(train_data.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1))

    model.compile(optimizer='rmsprop',
              loss='mse',
              metrics=['mae'])
    return model

## K-fold validation

In [45]:
k = 4
num_val_samples = len(train_data) // k
num_epochs = 100
all_scores = []

for i in range(k):
    print(f'Processing fold # {i}')
    val_data = train_data[i * num_val_samples: (i+1) * num_val_samples]
    val_targets = train_targets[i * num_val_samples: (i+1) * num_val_samples]
    
    partial_train_data = np.concatenate(
                            [train_data[:i * num_val_samples],
                            train_data[(i+1) * num_val_samples:]],
                            axis=0)
    partial_train_targets = np.concatenate(
                            [train_targets[:i * num_val_samples],
                            train_targets[(i+1)*num_val_samples:]],
                            axis=0)
    model = build_model()
    model.fit(partial_train_data,
              partial_train_targets,
              epochs=num_epochs,
              batch_size=1,
              verbose=0)
    val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
    all_scores.append(val_mae)


Processing fold # 0
Processing fold # 1
Processing fold # 2
Processing fold # 3


In [47]:
print(f'all_scores : {all_scores}')
print(f'mean all scores : {np.mean(all_scores)}')

all_scores : [2.7037034034729004, 2.107163190841675, 2.6224045753479004, 2.3437278270721436]
mean all scores : 2.444249749183655


In [48]:
model = build_model()
model.fit(train_data, train_targets, epochs=80, batch_size=16, verbose=0)
test_mse_score, test_mae_score = model.evaluate(test_data, test_targets)

102/102 [==============================] - 0s 206us/step


In [49]:
test_mae_score

2.7515878677368164

In [90]:
X = df.iloc[:,0:13].values
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [91]:
Y = df.iloc[:,13].values
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [93]:
from keras.models import Sequential
from keras.layers import Dense

In [94]:
model = Sequential()
model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model asking for accuracy, too:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

model.fit(X, Y,
     batch_size=5,
     epochs=100,
     verbose=1)

Epoch 1/100
506/506 [==============================] - 1s 1ms/step - loss: 201.0550 - accuracy: 0.0040
Epoch 2/100
506/506 [==============================] - 0s 499us/step - loss: 90.3587 - accuracy: 0.0099
Epoch 3/100
506/506 [==============================] - 0s 539us/step - loss: 75.3167 - accuracy: 0.0158
Epoch 4/100
506/506 [==============================] - 0s 534us/step - loss: 70.3445 - accuracy: 0.0138
Epoch 5/100
506/506 [==============================] - 0s 587us/step - loss: 64.9320 - accuracy: 0.0040
Epoch 6/100
506/506 [==============================] - 0s 568us/step - loss: 62.7500 - accuracy: 0.0079
Epoch 7/100
506/506 [==============================] - 0s 534us/step - loss: 60.3115 - accuracy: 0.0059
Epoch 8/100
506/506 [==============================] - 0s 553us/step - loss: 57.3647 - accuracy: 0.0158
Epoch 9/100
506/506 [==============================] - 0s 598us/step - loss: 55.2052 - accuracy: 0.0059
Epoch 10/100
506/506 [==============================] - 0s 529us/

In [95]:
score = model.evaluate(X, Y, verbose=0)
score

[15.883681466928113, 0.013833992183208466]

In [96]:
def binary_accuracy(y_true, y_pred):
    return K.mean(K.equal(y_true, K.round(y_pred)), axis=-1)

In [97]:
y_pred = model.predict(X)
l = len(Y)
acc = sum([np.round(y_pred[i])==Y[i] for i in range(l)])/l
acc

array([0.01383399])

In [101]:
from matplotlib import pyplot as plt

In [102]:
plt.plot(hist.history['acc'])
plt.plot(hist.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='lower right')
plt.show()

NameError: name 'hist' is not defined

In [20]:
import keras as kr
import pandas as pd
import numpy as np
import sklearn.preprocessing as pre
import sklearn.model_selection as mod
import sklearn.decomposition as dec

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8

In [21]:
from sklearn.datasets import load_boston

In [24]:
df = pd.DataFrame(df.load_boston)
df.columns = df.feature_names

AttributeError: load_boston

In [25]:
load_boston()

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p