# Dogs

In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8

# Preparing

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ianmcloughlin/datasets/master/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
5    True    5   14.11    26.9        12
6   False    8    9.51    49.2        15
7    True    3   15.60    49.9        11
8    True    4   12.36    48.1        13
9   False    5   19.18    54.2        10
10  False    5   15.98    57.2        12
11   True    6    4.85    56.7        17
12  False    3   19.52    43.0        10
13  False    3   11.21    57.2        14
14   True    1   14.08    47.7        12
15   True    4   14.96    59.3        11
16   True    3    6.84    42.5        16
17  False    8   15.76    46.8        12
18  False    7   17.78    39.8        11
19  False    2   21.49    59.5        10
20  False    5   16.26    42.8        12
21  False    3   17.82    45.1        11
22   True    6    7.90    44.1        15
23  False    5   18.26    50.4        11
24  False    3   18.56    61.0        11
25  False    4   11.95    54.9        14
26  False    4   11.09    46.1        15
27   True    8   15.57    48.0        11
28  False    2    6.97    40.1        17
29  False    5   19.78    49.0        10
..    ...  ...     ...     ...       ...
70   True    3   15.49    41.9        11
71  False    5    8.84    53.4        16
72  False    2   13.85    36.0        13
73  False    0   17.10    60.3        12
74  False    3   16.12    28.4        12
75   True    0    3.67    46.9        18
76  False    2   14.98    46.7        12
77  False    3    8.28    41.3        16
78   True    6   16.25    44.6        11
79   True    4   21.81    52.0         8
80   True    6   21.88    43.0         8
81   True    6   14.21    63.4        12
82  False    3    5.05    55.7        18
83   True    4   19.55    41.0         9
84   True    5    6.60    48.1        16
85  False    6   13.39    65.1        13
86   True    4   20.90    52.0         9
87  False    2    8.02    48.2        16
88   True    3   19.38    63.5         9
89   True    6   16.52    51.5        11
90  False    7    9.02    58.3        16
91  False    6   13.38    63.3        13
92   True    1   21.50    55.7         8
93   True    6   10.55    44.6        14
94  False    4   11.00    43.7        15
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

In [3]:
pureenc = pre.LabelBinarizer()
pureenc.fit(df['pure'])
df['pureenc'] = pureenc.transform(df['pure'])

In [4]:
x = df[['pureenc', 'age', 'weight', 'height']]
y = df['lifespan']

In [5]:
x

pureenc  age  weight  height
0         1    3    7.94    49.6
1         1    7    5.05    63.5
2         1    6   16.15    68.2
3         0    3   15.50    64.7
4         0    3   12.17    59.7
5         1    5   14.11    26.9
6         0    8    9.51    49.2
7         1    3   15.60    49.9
8         1    4   12.36    48.1
9         0    5   19.18    54.2
10        0    5   15.98    57.2
11        1    6    4.85    56.7
12        0    3   19.52    43.0
13        0    3   11.21    57.2
14        1    1   14.08    47.7
15        1    4   14.96    59.3
16        1    3    6.84    42.5
17        0    8   15.76    46.8
18        0    7   17.78    39.8
19        0    2   21.49    59.5
20        0    5   16.26    42.8
21        0    3   17.82    45.1
22        1    6    7.90    44.1
23        0    5   18.26    50.4
24        0    3   18.56    61.0
25        0    4   11.95    54.9
26        0    4   11.09    46.1
27        1    8   15.57    48.0
28        0    2    6.97    40.1
29        0    5   19.78    49.0
..      ...  ...     ...     ...
70        1    3   15.49    41.9
71        0    5    8.84    53.4
72        0    2   13.85    36.0
73        0    0   17.10    60.3
74        0    3   16.12    28.4
75        1    0    3.67    46.9
76        0    2   14.98    46.7
77        0    3    8.28    41.3
78        1    6   16.25    44.6
79        1    4   21.81    52.0
80        1    6   21.88    43.0
81        1    6   14.21    63.4
82        0    3    5.05    55.7
83        1    4   19.55    41.0
84        1    5    6.60    48.1
85        0    6   13.39    65.1
86        1    4   20.90    52.0
87        0    2    8.02    48.2
88        1    3   19.38    63.5
89        1    6   16.52    51.5
90        0    7    9.02    58.3
91        0    6   13.38    63.3
92        1    1   21.50    55.7
93        1    6   10.55    44.6
94        0    4   11.00    43.7
95        0    4   20.76    52.2
96        0    4   17.40    47.5
97        0    6   15.60    51.4
98        0    3    8.37    54.1
99        1    7    9.09    50.3

[100 rows x 4 columns]

In [6]:
y

0     15
1     17
2     11
3     12
4     14
5     12
6     15
7     11
8     13
9     10
10    12
11    17
12    10
13    14
14    12
15    11
16    16
17    12
18    11
19    10
20    12
21    11
22    15
23    11
24    11
25    14
26    15
27    11
28    17
29    10
      ..
70    11
71    16
72    13
73    12
74    12
75    18
76    12
77    16
78    11
79     8
80     8
81    12
82    18
83     9
84    16
85    13
86     9
87    16
88     9
89    11
90    16
91    13
92     8
93    14
94    15
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [7]:
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

# Building & Training

In [8]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 236.4497
Epoch 2/100
70/70 [==============================] - 0s 357us/step - loss: 187.2551
Epoch 3/100
70/70 [==============================] - 0s 214us/step - loss: 143.4153
Epoch 4/100
70/70 [==============================] - 0s 636us/step - loss: 107.5923
Epoch 5/100
70/70 [==============================] - 0s 764us/step - loss: 79.3718
Epoch 6/100
70/70 [==============================] - 0s 464us/step - loss: 59.3345
Epoch 7/100
70/70 [==============================] - 0s 214us/step - loss: 44.8053
Epoch 8/100
70/70 [==============================] - 0s 679us/step - loss: 35.2518
Epoch 9/100
70/70 [==============================] - 0s 321us/step - loss: 29.8985
Epoch 10/100
70/70 [==============================] - 0s 636us/step - loss: 26.5177
Epoch 11/100
70/70 [==============================] - 0s 507us/step - loss: 24.6046
Epoch 12/100
70/70 [===============

70/70 [==============================] - 0s 607us/step - loss: 9.6856
Epoch 96/100
70/70 [==============================] - 0s 357us/step - loss: 9.6445
Epoch 97/100
70/70 [==============================] - 0s 321us/step - loss: 9.6104
Epoch 98/100
70/70 [==============================] - ETA: 0s - loss: 7.543 - 0s 250us/step - loss: 9.5718
Epoch 99/100
70/70 [==============================] - 0s 357us/step - loss: 9.5621
Epoch 100/100
70/70 [==============================] - 0s 571us/step - loss: 9.4986


In [10]:
m.predict(x_test).round().T

array([[12., 12., 10., 11., 14., 13., 11., 11., 11., 12.,  7.,  9., 14.,
        14., 13., 17., 14.,  8., 17., 11., 11.,  7., 13., 15., 13., 14.,
        13.,  9., 11., 12.]], dtype=float32)

In [11]:
y_test.as_matrix().astype(np.float32)

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 8., 16., 11., 11., 11., 10., 12., 11., 12., 14., 12., 10., 12.,
       12., 16., 13., 11., 11., 17., 14., 12.,  8., 14.,  9., 12., 11.,
       10., 12., 14., 14.], dtype=float32)

In [12]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 2ms/step


7.114660263061523

# Scaling

In [13]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [14]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [15]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 23.8457
Epoch 2/100
70/70 [==============================] - 0s 143us/step - loss: 21.0670
Epoch 3/100
70/70 [==============================] - 0s 286us/step - loss: 20.0956
Epoch 4/100
70/70 [==============================] - 0s 643us/step - loss: 19.1124
Epoch 5/100
70/70 [==============================] - 0s 464us/step - loss: 17.8667
Epoch 6/100
70/70 [==============================] - 0s 321us/step - loss: 17.1097
Epoch 7/100
70/70 [==============================] - 0s 750us/step - loss: 16.3767
Epoch 8/100
70/70 [==============================] - 0s 943us/step - loss: 15.8600
Epoch 9/100
70/70 [==============================] - 0s 507us/step - loss: 15.1688
Epoch 10/100
70/70 [==============================] - 0s 500us/step - loss: 14.6819
Epoch 11/100
70/70 [==============================] - 0s 464us/step - loss: 14.0977
Epoch 12/100
70/70 [==============================] - 0s 557us/step - loss: 13.5487
Epo

70/70 [==============================] - 0s 443us/step - loss: 7.4554
Epoch 99/100
70/70 [==============================] - 0s 400us/step - loss: 7.5442
Epoch 100/100
70/70 [==============================] - 0s 714us/step - loss: 7.5124


In [16]:
m.predict(x_test).round().T

array([[12., 14.,  9., 11., 14., 12., 11., 10., 11., 12.,  6.,  8., 13.,
        13., 14., 18., 13.,  8., 20., 11., 11.,  8., 14., 13., 12., 14.,
        12.,  8., 12., 13.]], dtype=float32)

In [17]:
y_test.as_matrix().astype(np.float32)

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 8., 16., 11., 11., 11., 10., 12., 11., 12., 14., 12., 10., 12.,
       12., 16., 13., 11., 11., 17., 14., 12.,  8., 14.,  9., 12., 11.,
       10., 12., 14., 14.], dtype=float32)

In [18]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 4ms/step


6.6354079246521

# Whitening

In [19]:
pca = dec.PCA(n_components=4, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

pureenc       age    weight    height
0  -0.255943 -1.359423 -0.344685  1.255153
1  -0.657495 -0.080413 -0.273236 -0.909354
2  -0.635801  1.837740 -0.582256 -1.079986
3   0.508713  0.553464  0.049854 -0.876329
4   1.359626 -0.333958 -0.972478 -0.735647
5   1.114308  1.088098 -0.304306 -0.879177
6  -0.279281 -1.331792 -0.345685 -0.769087
7   0.203856 -0.571789  0.942531 -0.796181
8  -0.245755  0.859894 -0.072567  1.058586
9   0.830651 -1.638427  0.944425  1.366706
10  0.987892 -0.877008  0.523845 -0.710670
11 -1.619278  0.204183  0.652381 -1.004929
12  1.097072 -1.170268 -0.036291  1.342043
13 -0.572769  0.446044 -0.191324 -0.949673
14 -0.054058 -0.854906  0.306761 -0.792502
15 -1.839790  0.215320  0.607224 -1.022822
16 -2.051684 -0.182700 -0.033378  1.014596
17  0.608573 -0.787995 -0.639195 -0.751115
18 -1.623252 -0.123337 -2.123510  1.035250
19 -1.052281  0.319524  1.879303  1.051724
20  0.803053  0.553915  0.111992 -0.853807
21  1.234676 -0.854223  1.672529 -0.690326
22 -0.260439 -1.118077  1.872006 -0.779739
23  0.110997 -1.168454  0.303433 -0.751969
24  0.331640  0.613206 -0.527158 -0.896941
25  1.009794 -0.344596 -0.501191  1.260205
26 -0.453853  1.163523 -0.625894 -1.006086
27  0.257816  0.316379 -0.032468  1.145516
28 -0.845548  0.619385 -0.774703 -0.987723
29  1.947979  1.055678  0.960891  1.211055
..       ...       ...       ...       ...
40  1.272627  1.349654 -0.786025 -0.892027
41  0.029467 -0.308182 -0.703537  1.181824
42  0.098570  1.218270 -0.503276  1.051384
43 -0.381713  1.046850  0.468989 -0.986727
44 -1.635599  0.041043  0.628532  1.028321
45  2.661218 -0.570579 -0.179795 -0.613110
46 -1.155810  0.446045 -0.861231 -0.996091
47 -2.231712 -0.311086  0.459962  1.013940
48  0.464730  2.077357 -1.962330  0.997877
49 -0.775424  1.860057  1.031238  0.932502
50  0.332662  2.162670 -0.885948  0.983621
51  0.380023 -0.408925  2.093360 -0.793706
52 -0.994252  1.028907  1.431467 -1.028630
53 -0.418754 -0.409085  0.830438  1.161620
54  0.112466  0.855844  2.190779 -0.926682
55 -0.617097 -0.412295 -1.399508  1.139795
56  0.754976  1.159468  1.268813  1.112108
57  0.233280 -0.360487  2.067740  1.210732
58  0.316962 -0.003128 -1.699648  1.173280
59 -0.866885 -1.547316 -1.042772 -0.796689
60  0.310582 -0.695555 -0.143874 -0.780449
61  1.745744 -0.053241 -0.856889 -0.731012
62  0.516433 -1.350735 -1.274014 -0.709864
63 -0.259787 -1.541024 -0.367586  1.271007
64 -0.015251  0.958338  1.628817  1.072681
65 -1.402531 -1.143479  0.534161 -0.868477
66 -0.877310 -0.350295  0.194500 -0.900477
67  0.219293 -0.924164 -0.191499  1.252876
68 -0.158987 -0.569183  0.318824  1.194041
69 -0.652272  1.402105 -1.186214  0.975757

[70 rows x 4 columns]

In [20]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=4, activation="tanh"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [21]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 3ms/step - loss: 161.8023
Epoch 2/100
70/70 [==============================] - 0s 214us/step - loss: 138.3464
Epoch 3/100
70/70 [==============================] - 0s 357us/step - loss: 117.0912
Epoch 4/100
70/70 [==============================] - 0s 393us/step - loss: 98.1969
Epoch 5/100
70/70 [==============================] - 0s 250us/step - loss: 81.4685
Epoch 6/100
70/70 [==============================] - 0s 350us/step - loss: 65.0550
Epoch 7/100
70/70 [==============================] - 0s 614us/step - loss: 48.4996
Epoch 8/100
70/70 [==============================] - 0s 643us/step - loss: 34.9513
Epoch 9/100
70/70 [==============================] - 0s 607us/step - loss: 25.6854
Epoch 10/100
70/70 [==============================] - 0s 429us/step - loss: 18.9697
Epoch 11/100
70/70 [==============================] - 0s 479us/step - loss: 14.9019
Epoch 12/100
70/70 [==============================] - 0s 343us/step - loss: 12.3827


70/70 [==============================] - 0s 922us/step - loss: 1.2922
Epoch 100/100
70/70 [==============================] - 0s 357us/step - loss: 1.2832


In [22]:
m.predict(x_test).round().T

array([[10., 15., 11., 11., 11., 11., 11., 11., 11., 14., 10., 11., 12.,
        12., 16., 14., 12., 10., 17., 13., 11.,  9., 13., 11., 12., 12.,
        11., 11., 13., 14.]], dtype=float32)

In [23]:
y_test.as_matrix().astype(np.float32)

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 8., 16., 11., 11., 11., 10., 12., 11., 12., 14., 12., 10., 12.,
       12., 16., 13., 11., 11., 17., 14., 12.,  8., 14.,  9., 12., 11.,
       10., 12., 14., 14.], dtype=float32)

In [24]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 3ms/step


0.7366605401039124