In [1]:
# For building neural networks.
import keras as kr

# For interacting with data sets.
import pandas as pd

# For encoding categorical variables.
import sklearn.preprocessing as pre

# For splitting into training and test sets.
import sklearn.model_selection as mod

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8


## Load data

In [2]:
# Load the iris data set from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [3]:
# Separate the inputs from the rest of the variables.
inputs = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]

In [4]:
inputs

petal_length  petal_width  sepal_length  sepal_width
0             1.4          0.2           5.1          3.5
1             1.4          0.2           4.9          3.0
2             1.3          0.2           4.7          3.2
3             1.5          0.2           4.6          3.1
4             1.4          0.2           5.0          3.6
5             1.7          0.4           5.4          3.9
6             1.4          0.3           4.6          3.4
7             1.5          0.2           5.0          3.4
8             1.4          0.2           4.4          2.9
9             1.5          0.1           4.9          3.1
10            1.5          0.2           5.4          3.7
11            1.6          0.2           4.8          3.4
12            1.4          0.1           4.8          3.0
13            1.1          0.1           4.3          3.0
14            1.2          0.2           5.8          4.0
15            1.5          0.4           5.7          4.4
16            1.3          0.4           5.4          3.9
17            1.4          0.3           5.1          3.5
18            1.7          0.3           5.7          3.8
19            1.5          0.3           5.1          3.8
20            1.7          0.2           5.4          3.4
21            1.5          0.4           5.1          3.7
22            1.0          0.2           4.6          3.6
23            1.7          0.5           5.1          3.3
24            1.9          0.2           4.8          3.4
25            1.6          0.2           5.0          3.0
26            1.6          0.4           5.0          3.4
27            1.5          0.2           5.2          3.5
28            1.4          0.2           5.2          3.4
29            1.6          0.2           4.7          3.2
..            ...          ...           ...          ...
120           5.7          2.3           6.9          3.2
121           4.9          2.0           5.6          2.8
122           6.7          2.0           7.7          2.8
123           4.9          1.8           6.3          2.7
124           5.7          2.1           6.7          3.3
125           6.0          1.8           7.2          3.2
126           4.8          1.8           6.2          2.8
127           4.9          1.8           6.1          3.0
128           5.6          2.1           6.4          2.8
129           5.8          1.6           7.2          3.0
130           6.1          1.9           7.4          2.8
131           6.4          2.0           7.9          3.8
132           5.6          2.2           6.4          2.8
133           5.1          1.5           6.3          2.8
134           5.6          1.4           6.1          2.6
135           6.1          2.3           7.7          3.0
136           5.6          2.4           6.3          3.4
137           5.5          1.8           6.4          3.1
138           4.8          1.8           6.0          3.0
139           5.4          2.1           6.9          3.1
140           5.6          2.4           6.7          3.1
141           5.1          2.3           6.9          3.1
142           5.1          1.9           5.8          2.7
143           5.9          2.3           6.8          3.2
144           5.7          2.5           6.7          3.3
145           5.2          2.3           6.7          3.0
146           5.0          1.9           6.3          2.5
147           5.2          2.0           6.5          3.0
148           5.4          2.3           6.2          3.4
149           5.1          1.8           5.9          3.0

[150 rows x 4 columns]

## Encoded outputs
<p>setosa→[1,0,0]</p>
<p>versicolor→[0,1,0]</p>
<p>virginica→[0,0,1]</p>

In [5]:
# Encode the classes as above.
encoder = pre.LabelBinarizer()
encoder.fit(df['species'])
outputs = encoder.transform(df['species'])

outputs

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

## Idea

<p>The neural network will turn four floating point inputs into three "floating point" outputs.</p>
<p>[5.1,3.5,1.4,0.2]→[0.8,0.19,0.01]</p>
<p>[5.1,3.5,1.4,0.2]→[1,0,0]</p>

## Build the model

In [8]:
# Start a neural network, building it by layers.
model = kr.models.Sequential()

# Add a hidden layer with 64 neurons and an input layer with 4.
model.add(kr.layers.Dense(units=64, activation='relu', input_dim=4))
# Add a three neuron output layer.
model.add(kr.layers.Dense(units=3, activation='softmax'))

# Build the graph.
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


## Split

In [6]:
# Split the inputs and outputs into training and test sets.
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.5)

In [10]:
inputs_test.iloc[0]

petal_length    4.8
petal_width     1.8
sepal_length    5.9
sepal_width     3.2
Name: 70, dtype: float64

In [11]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.49351442, 0.08128997, 0.42519557]], dtype=float32)

## Train

In [13]:
# Train the neural network.
model.fit(inputs_train, outputs_train, epochs=15, batch_size=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/15
75/75 [==============================] - 0s 2ms/step - loss: 1.3346 - accuracy: 0.1867
Epoch 2/15
75/75 [==============================] - 0s 167us/step - loss: 1.1219 - accuracy: 0.3600
Epoch 3/15
75/75 [==============================] - 0s 167us/step - loss: 1.0146 - accuracy: 0.4133
Epoch 4/15
75/75 [==============================] - 0s 300us/step - loss: 0.9385 - accuracy: 0.4933
Epoch 5/15
75/75 [==============================] - 0s 267us/step - loss: 0.8588 - accuracy: 0.7600
Epoch 6/15
75/75 [==============================] - 0s 367us/step - loss: 0.7902 - accuracy: 0.8133
Epoch 7/15
75/75 [==============================] - 0s 267us/step - loss: 0.7506 - accuracy: 0.7200
Epoch 8/15
75/75 [==============================] - 0s 200us/step - loss: 0.7055 - accuracy: 0.8000
Epoch 9/15
75/75 [==============================] - 0s 233us/step - loss: 0.6865 - accuracy: 0.7200
Epoch 10/15
75/75 [==============================] - 0

## Predict

In [14]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.09010007, 0.49817812, 0.41172192]], dtype=float32)

In [15]:
# Have the network predict the classes of the test inputs.
predictions = model.predict(inputs_test)
predictions_labels = encoder.inverse_transform(predictions)
predictions_labels

array(['versicolor', 'versicolor', 'virginica', 'versicolor', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'setosa', 'versicolor', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'seto

## Evaluate

In [16]:
# Compare the predictions to the actual classes.
predictions_labels == encoder.inverse_transform(outputs_test)

array([ True, False,  True, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True, False, False,  True,  True, False,  True,  True,
       False,  True,  True])

In [17]:
(predictions_labels == encoder.inverse_transform(outputs_test)).sum()

55