In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec
from sklearn.datasets import load_boston #load the boston house proce index from the sklearn library

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8

In [2]:
boston_dataset = load_boston()
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [3]:
boston['MEDV'] = boston_dataset.target 

In [4]:
x = boston.iloc[:,0:13]
y = boston.iloc[:,13]

In [5]:
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

In [8]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))
#m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")

In [9]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
354/354 [==============================] - 0s 508us/step - loss: 2.0411
Epoch 2/100
354/354 [==============================] - 0s 169us/step - loss: 1.6628
Epoch 3/100
354/354 [==============================] - 0s 141us/step - loss: 1.3536
Epoch 4/100
354/354 [==============================] - 0s 113us/step - loss: 1.2349
Epoch 5/100
354/354 [==============================] - 0s 141us/step - loss: 1.0630
Epoch 6/100
354/354 [==============================] - 0s 113us/step - loss: 0.9403
Epoch 7/100
354/354 [==============================] - 0s 113us/step - loss: 0.8175
Epoch 8/100
354/354 [==============================] - 0s 141us/step - loss: 0.7099
Epoch 9/100
354/354 [==============================] - 0s 169us/step - loss: 0.6460
Epoch 10/100
354/354 [==============================] - 0s 198us/step - loss: 0.6215
Epoch 11/100
354/354 [==============================] - ETA: 0s - loss: 0.600 - 0s 169us/step - loss: 0.5975
Epoch 12/100
354/354 [============================

354/354 [==============================] - 0s 226us/step - loss: 0.0534
Epoch 98/100
354/354 [==============================] - 0s 141us/step - loss: 0.0506
Epoch 99/100
354/354 [==============================] - 0s 113us/step - loss: 0.0500
Epoch 100/100
354/354 [==============================] - 0s 141us/step - loss: 0.0529


In [10]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [13]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))
#m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")

In [14]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
354/354 [==============================] - 0s 480us/step - loss: 8.5117
Epoch 2/100
354/354 [==============================] - 0s 113us/step - loss: 0.7500
Epoch 3/100
354/354 [==============================] - 0s 169us/step - loss: 0.4583
Epoch 4/100
354/354 [==============================] - 0s 169us/step - loss: 0.2484
Epoch 5/100
354/354 [==============================] - 0s 141us/step - loss: 0.2260
Epoch 6/100
354/354 [==============================] - 0s 141us/step - loss: 0.2142
Epoch 7/100
354/354 [==============================] - 0s 113us/step - loss: 0.2066
Epoch 8/100
354/354 [==============================] - 0s 141us/step - loss: 0.2017
Epoch 9/100
354/354 [==============================] - 0s 113us/step - loss: 0.1990
Epoch 10/100
354/354 [==============================] - 0s 141us/step - loss: 0.1890
Epoch 11/100
354/354 [==============================] - 0s 141us/step - loss: 0.1821
Epoch 12/100
354/354 [==============================] - 0s 169us/step - lo

354/354 [==============================] - 0s 226us/step - loss: 0.0483
Epoch 98/100
354/354 [==============================] - 0s 141us/step - loss: 0.0491
Epoch 99/100
354/354 [==============================] - 0s 113us/step - loss: 0.0495
Epoch 100/100
354/354 [==============================] - 0s 113us/step - loss: 0.0476


In [15]:
m.predict(x_test).round().T

array([[15.,  9., 15., 12., 18., 13., 24., 17., 12., 16., 32., 21., 25.,
        27., 21., 15., 23., 16.,  5., 14., 11., 25., 25., 25., 27., 22.,
        13., 22., 16., 20., 22., 17., 20.,  7., 25., 16., 22., 24., 23.,
        21., 19., 21., 21., 25., 22., 23., 20., 27., 24., 25., 23., 17.,
        18., 24., 16., 21., 18., 26., 17., 20., 33., 16., 16., 25., 16.,
        14., 19., 18., 27., 20., 24., 22., 22., 13., 26., 23., 18., 27.,
        25., 28., 19., 19., 10., 30., 36., 26., 22., 13., 15., 22., 24.,
        24., 19., 25., 24., 23., 17., 28., 20., 23., 25., 17., 19., 23.,
        10., 21., 26., 18., 27., 25., 12., 24., 25., 18., 17., 22., 15.,
        19., 22., 21., 24., 21., 20., 13., 19., 27., 24., 18., 26., 16.,
        28., 16., 14., 14., 20., 24., 23.,  7., 20., 41., 22., 29., 12.,
        23., 21., 20., 18., 18., 18., 17., 22., 32.]], dtype=float32)

In [16]:
y_test.as_matrix().astype(np.float32)

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([27.5, 17.8, 12.7, 12. , 15.6,  8.3, 23.9, 16.1, 11.8, 20.4, 31.6,
       22.6, 23.7, 42.3, 24. , 13.8, 29. ,  8.5, 13.2, 15.6, 14.6, 48.8,
       50. , 24.8, 23.4, 22. , 12.8, 28.7, 17. , 22.7, 20. , 19.9, 21.2,
        6.3, 29. , 13.4, 19.9, 25.1, 22.2, 20.3, 22. , 20.5, 30.3, 25. ,
       25. , 21.6, 18.2, 33.4, 32. , 23.1, 24.1, 15. , 17.7, 19. ,  9.6,
       22.9, 16.6, 37.6, 20. , 20.8, 37.3, 12.7, 14.9, 34.7, 13.6,  9.5,
       27.5, 15.2, 35.2, 18.2, 23.9, 20.9, 23.8,  7.5, 44.8, 22.6, 16.8,
       32. , 48.3, 50. , 19.6, 21.8,  8.4, 33.1, 30.1, 50. , 23.3, 14.8,
       14.1, 24.5, 41.3, 24.6, 15.3, 23. , 36.5, 27.1, 17.8, 26.6, 23.1,
       18.9, 23.7, 19.1, 17.5, 50. ,  5.6, 28.4, 36.2, 19.5, 43.5, 25. ,
        7. , 18.7, 50. , 22.5, 19.9, 26.5, 14.1, 20. , 24.3, 20.1, 36. ,
       21.7, 21.8, 20.2, 17.6, 50. , 29.9, 18.9, 33.3, 16.7, 50. , 12.5,
       19.4, 13.4, 19.8, 26.6, 23.9,  8.8, 18.9, 50. , 21.7, 36.1, 17.2,
       18.2, 20.3, 21.7, 21.4, 20.6, 13.8, 13.4, 23

In [17]:
pca = dec.PCA(n_components=13, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.779282  0.046682 -1.372281  0.526056 -0.098318 -0.518909  0.701723   
1   -1.143789  0.226200  0.524269 -0.700368  0.429386 -0.554615 -0.340130   
2   -0.207060 -0.351878 -0.659215 -0.086648 -0.453202 -0.790520 -0.056720   
3   -0.759802  0.012021  0.801030 -2.440905  0.227237 -0.040985  0.409850   
4   -1.192579  0.779302 -1.818313  0.794719  0.429588  3.154097  1.839061   
5   -1.228604  0.426378 -0.979864 -0.247193  0.459192 -0.066192 -1.448980   
6   -0.684186 -0.017125 -0.633368 -0.390375 -0.004051 -0.724386 -0.940293   
7   -0.832640  0.042129 -0.555234 -0.578430  0.002527 -1.195204 -0.396563   
8   -0.525737 -0.050751  1.643198 -1.720299  0.040105 -0.153797  0.232904   
9    0.135853  0.079028 -0.702650  0.183677 -0.684583  0.049694 -0.398385   
10  -0.823014  0.072077 -0.853458 -0.163122 -0.010287 -1.006865 -0.681461   
11  -1.094559  0.201951 -0.257788  1.426358  0.237420 -1.187836 -1.123423   
12  -0.532247 -0.143635  1.335205 -1.305557  0.080791  0.128988 -0.074948   
13   0.032189 -0.364214  0.984574 -2.175333 -0.364840  0.176266 -0.595259   
14  -0.970383  0.111723  2.256356  1.321040  0.183366 -0.190510  0.615912   
15  -0.802024  0.010558 -0.519852 -0.606740 -0.001044 -1.135421 -0.529680   
16   0.050000 -0.483395 -0.117858 -0.686213 -0.485919  0.258766 -0.056492   
17   0.056649 -0.550090 -0.949781  0.466610 -0.554758  0.164951 -0.562458   
18  -1.088007  0.197458 -0.273877 -1.154001  0.424371 -0.010448 -0.725374   
19   1.327613 -1.388404 -0.388812  0.388301  0.430668  2.602374 -1.845792   
20  -0.176383 -0.402101 -0.406060 -0.431329 -0.300219  0.251357 -0.253567   
21   1.307242 -1.388448  0.623496 -0.991475 -0.245434 -0.244169  0.040102   
22   1.887831  2.890825  0.120417  0.112988 -0.748978  0.487974 -0.931154   
23   1.324486 -1.389708 -0.293408  0.284724 -0.142051 -0.198274 -0.538138   
24   1.354292 -1.157860 -0.238734  0.230908 -0.238265 -0.273054 -0.496439   
25  -0.794372  0.043294  0.341218 -1.828265  0.292837  0.393407 -0.381963   
26  -0.963710  0.126650 -0.173215 -1.211778  0.366479  0.521503 -0.821885   
27   1.335881 -1.378706 -0.142699  0.172779  9.548751 -2.106839  3.086271   
28  -0.725638  0.040122 -0.828401 -0.168590  0.047003 -0.256251 -0.571609   
29   1.944091  3.220617 -0.011147  0.412146  6.715380 -1.725246  2.060730   
..        ...       ...       ...       ...       ...       ...       ...   
324 -1.232009  0.306020 -1.686558  0.743732  0.178276 -1.958307 -1.010054   
325 -0.769544  0.057371  0.933577 -0.661311  0.224153 -0.087678 -0.478583   
326  0.053307 -0.520964 -0.578466 -0.038520 -0.646167 -0.708205  0.093579   
327  1.432705 -0.568338  0.080970 -0.138245  3.869644  0.864978  0.203564   
328 -0.745274 -0.028938 -0.277603 -0.938707  0.054226 -0.635744 -0.015857   
329 -0.055075 -0.113322 -1.025686  0.491396 -0.674822 -1.648724  2.620455   
330  1.341204 -1.224549  0.022587 -0.127594  0.381066 -0.950163  0.185944   
331 -1.081127  0.284585 -0.029754 -1.477303  0.362155 -0.542538 -0.341556   
332  1.917618  3.083110 -0.026130  0.336896  0.191708  1.046975 -1.067334   
333 -0.943718  0.089435  1.055180  0.231361  0.245461  0.226678  0.361266   
334 -0.451828 -0.226744  1.069412 -1.633190 -0.023538  0.334185  0.113803   
335 -1.229351  0.339765 -1.589406  0.612354  0.169645 -2.038777 -0.909218   
336  1.325440 -1.388607 -0.261335  0.259238  1.008627 -1.245808  0.330217   
337 -0.862539  0.107514 -0.161533  0.416875  0.231116 -0.318603 -0.779385   
338  1.324139 -1.315316  0.203130 -0.399848 -0.795696 -0.622838 -0.178703   
339 -0.160398 -0.339631  1.703937  0.246093 -0.397896 -0.496996  0.061063   
340  0.057301 -0.196862  0.829021 -1.937920 -0.458902 -0.137875 -0.581508   
341 -0.978439  0.163443 -0.212725  0.489275  0.182439 -0.284891 -0.421324   
342 -0.624002 -0.102098 -0.925545  0.041010 -0.046906 -1.334314 -0.767389   
343  1.946965  3.381152  0.423799 -0.267636 -1.254834  0.639363 -0.961160   
344 -

In [20]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))
#m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")

In [21]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
354/354 [==============================] - 0s 565us/step - loss: 2.8666
Epoch 2/100
354/354 [==============================] - 0s 141us/step - loss: 1.1722
Epoch 3/100
354/354 [==============================] - 0s 141us/step - loss: 0.7981
Epoch 4/100
354/354 [==============================] - 0s 141us/step - loss: 0.7294
Epoch 5/100
354/354 [==============================] - 0s 169us/step - loss: 0.7051
Epoch 6/100
354/354 [==============================] - 0s 229us/step - loss: 0.6937
Epoch 7/100
354/354 [==============================] - 0s 226us/step - loss: 0.6937
Epoch 8/100
354/354 [==============================] - 0s 198us/step - loss: 0.6926
Epoch 9/100
354/354 [==============================] - 0s 169us/step - loss: 0.6696
Epoch 10/100
354/354 [==============================] - 0s 169us/step - loss: 0.6385
Epoch 11/100
354/354 [==============================] - 0s 169us/step - loss: 0.6410
Epoch 12/100
354/354 [==============================] - 0s 169us/step - lo

354/354 [==============================] - 0s 141us/step - loss: 0.0501
Epoch 98/100
354/354 [==============================] - 0s 141us/step - loss: 0.0516
Epoch 99/100
354/354 [==============================] - 0s 198us/step - loss: 0.0469
Epoch 100/100
354/354 [==============================] - 0s 113us/step - loss: 0.0503


In [22]:
m.predict(x_test).round().T

array([[18., 15., 16., 16., 19., 17., 26., 19., 14., 22., 33., 27., 28.,
        32., 24., 19., 26., 19., 10., 13., 14., 32., 29., 27., 27., 25.,
        18., 25., 22., 22., 22., 22., 22., 15., 31., 18., 23., 27., 26.,
        24., 22., 21., 24., 27., 24., 25., 21., 28., 28., 27., 29., 19.,
        22., 25., 18., 23., 18., 30., 20., 22., 33., 20., 15., 27., 23.,
        17., 23., 19., 30., 22., 27., 23., 24., 16., 30., 25., 23., 31.,
        29., 31., 21., 23., 17., 32., 29., 33., 25., 12., 18., 21., 25.,
        27., 22., 26., 30., 24., 21., 28., 23., 25., 29., 21., 20., 27.,
        15., 23., 27., 21., 32., 25., 19., 26., 31., 19., 21., 23., 19.,
        21., 23., 20., 30., 23., 22., 16., 19., 28., 27., 19., 30., 20.,
        28., 20., 20., 17., 21., 24., 26., 13., 22., 38., 23., 32., 16.,
        24., 24., 21., 22., 23., 21., 14., 24., 33.]], dtype=float32)

In [23]:
y_test.as_matrix().astype(np.float32)

C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([27.5, 17.8, 12.7, 12. , 15.6,  8.3, 23.9, 16.1, 11.8, 20.4, 31.6,
       22.6, 23.7, 42.3, 24. , 13.8, 29. ,  8.5, 13.2, 15.6, 14.6, 48.8,
       50. , 24.8, 23.4, 22. , 12.8, 28.7, 17. , 22.7, 20. , 19.9, 21.2,
        6.3, 29. , 13.4, 19.9, 25.1, 22.2, 20.3, 22. , 20.5, 30.3, 25. ,
       25. , 21.6, 18.2, 33.4, 32. , 23.1, 24.1, 15. , 17.7, 19. ,  9.6,
       22.9, 16.6, 37.6, 20. , 20.8, 37.3, 12.7, 14.9, 34.7, 13.6,  9.5,
       27.5, 15.2, 35.2, 18.2, 23.9, 20.9, 23.8,  7.5, 44.8, 22.6, 16.8,
       32. , 48.3, 50. , 19.6, 21.8,  8.4, 33.1, 30.1, 50. , 23.3, 14.8,
       14.1, 24.5, 41.3, 24.6, 15.3, 23. , 36.5, 27.1, 17.8, 26.6, 23.1,
       18.9, 23.7, 19.1, 17.5, 50. ,  5.6, 28.4, 36.2, 19.5, 43.5, 25. ,
        7. , 18.7, 50. , 22.5, 19.9, 26.5, 14.1, 20. , 24.3, 20.1, 36. ,
       21.7, 21.8, 20.2, 17.6, 50. , 29.9, 18.9, 33.3, 16.7, 50. , 12.5,
       19.4, 13.4, 19.8, 26.6, 23.9,  8.8, 18.9, 50. , 21.7, 36.1, 17.2,
       18.2, 20.3, 21.7, 21.4, 20.6, 13.8, 13.4, 23

In [24]:
m.evaluate(x_test, y_test)

152/152 [==============================] - 0s 724us/step


0.07629462704062462

In [26]:
from scipy import stats

In [27]:
stats.ttest_ind(x_test, y_test)

Ttest_indResult(statistic=array([-22.77577605,  -5.53794422, -12.50693518, -27.70925837,
       -27.16708355, -20.23549301,  19.71647046, -22.81405217,
       -13.27528933,  27.94483704,  -6.25947823,  43.9926774 ,
       -11.2875507 ]), pvalue=array([1.57290413e-067, 6.65842010e-008, 3.32739670e-029, 6.15484129e-085,
       4.37837560e-083, 3.84965259e-058, 3.38781872e-056, 1.14065890e-067,
       5.38733362e-032, 9.75856339e-086, 1.32270946e-009, 2.31153632e-133,
       6.91235424e-025]))

In [28]:
stats.f_oneway(x_test, y_test)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [29]:


x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)



In [50]:


m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")



In [51]:


m.fit(x_train, y_train, epochs=100, batch_size=10)



Epoch 1/100
354/354 [==============================] - 0s 791us/step - loss: 1.5852
Epoch 2/100
354/354 [==============================] - 0s 169us/step - loss: 0.2164
Epoch 3/100
354/354 [==============================] - 0s 198us/step - loss: 0.1449
Epoch 4/100
354/354 [==============================] - 0s 169us/step - loss: 0.1322
Epoch 5/100
354/354 [==============================] - 0s 198us/step - loss: 0.1236
Epoch 6/100
354/354 [==============================] - 0s 169us/step - loss: 0.1201
Epoch 7/100
354/354 [==============================] - 0s 198us/step - loss: 0.1153
Epoch 8/100
354/354 [==============================] - 0s 169us/step - loss: 0.1084
Epoch 9/100
354/354 [==============================] - 0s 198us/step - loss: 0.1019
Epoch 10/100
354/354 [==============================] - 0s 198us/step - loss: 0.0979
Epoch 11/100
354/354 [==============================] - 0s 226us/step - loss: 0.0941
Epoch 12/100
354/354 [==============================] - 0s 169us/step - lo

354/354 [==============================] - 0s 254us/step - loss: 0.0520
Epoch 98/100
354/354 [==============================] - 0s 141us/step - loss: 0.0497
Epoch 99/100
354/354 [==============================] - 0s 141us/step - loss: 0.0521
Epoch 100/100
354/354 [==============================] - 0s 141us/step - loss: 0.0513


In [52]:
m.predict(x_test).round().T

array([[27., 22., 22., 21., 24., 16., 20., 23., 24., 23., 19., 14., 26.,
        22., 14., 23., 18., 25., 17., 30., 14., 26., 11., 19., 20., 24.,
        27., 24., 23., 19., 22., 19., 24., 22., 24., 27., 13., 10., 25.,
        20., 17., 23., 28., 26., 23., 18., 27., 27., 15., 20., 27.,  7.,
        10., 27., 22., 21., 33., 15., 24., 23., 19., 21., 18., 28., 27.,
        22., 24., 32., 31., 14., 26., 26., 26., 25., 14., 24., 16.,  7.,
        26., 15., 15., 21., 22., 16., 34., 16., 18., 33., 18., 18.,  4.,
        30., 23., 23., 18., 35., 16., 22., 26., 25., 25.,  8., 20., 20.,
        24., 19., 25., 18., 21., 27., 24., 28., 26., 23., 18., 23., 27.,
        26., 16., 13., 12., 22., 19., 31., 20., 24., 26., 29., 21., 21.,
        23., 24., 16., 13., 15., 30., 19., 28., 25., 32., 21., 36., 18.,
        30., 23., 26., 18., 26., 29., 15., 11., 26.]], dtype=float32)

In [53]:


y_test.as_matrix().astype(np.float32)



C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([24.8, 18.7, 16.1, 21. , 19.3, 13.4, 15. , 24.5, 16.8, 15.3, 20.3,
       13.4, 34.7, 18.7, 13.9, 17.1, 17.4, 21.8, 17.2, 20.7, 19.1, 22.2,
        5. , 15.4, 21.4, 17.4, 26.6, 24.5, 22. , 20.8, 21.5, 16.1, 20.9,
       19.5, 25. , 33.2,  7.2, 13.8, 20.1, 17.6, 10.9, 18.8, 28.7, 23.2,
       22.2, 14.9, 23.7, 28. ,  9.7, 23. , 50. , 13.8, 13.8, 26.7, 18.2,
       27.9, 32. ,  8.3, 18.9, 19.4, 11.5, 19.4, 20.4, 22. , 31.7, 21.2,
       19.7, 33.1, 26.4, 13.9, 21.1, 23.1, 26.6, 20.3,  8.7, 23.1, 10.8,
        7. , 25. , 17.3, 13.6, 17.7, 18.4, 13.1, 39.8, 20.1, 27.5, 50. ,
        7.2, 15. , 13.2, 33.1, 28.7, 30.3, 14.4, 43.1, 10.2, 21.2, 20.6,
       22.6, 21.7,  7.4, 13.1, 20. , 18.3, 21.2, 24.3, 19.8, 17.2, 22. ,
       23.4, 29.1, 23.8, 16.8, 13.4, 23.7, 20.9, 20.4, 13.1, 20.2, 10.4,
       22.4, 20.5, 24.5, 17.4, 18.5, 23.3, 23.5, 17. , 21.4, 21.7, 20.2,
       15.6, 15.7,  8.3, 29.8, 19.3, 26.2, 22.6, 34.9,  7. , 30.1,  9.6,
       31.2, 23.8, 21.9, 22.5, 23.9, 24.8, 15.6, 10

In [54]:


m.predict(x_test).round().T



array([[27., 22., 22., 21., 24., 16., 20., 23., 24., 23., 19., 14., 26.,
        22., 14., 23., 18., 25., 17., 30., 14., 26., 11., 19., 20., 24.,
        27., 24., 23., 19., 22., 19., 24., 22., 24., 27., 13., 10., 25.,
        20., 17., 23., 28., 26., 23., 18., 27., 27., 15., 20., 27.,  7.,
        10., 27., 22., 21., 33., 15., 24., 23., 19., 21., 18., 28., 27.,
        22., 24., 32., 31., 14., 26., 26., 26., 25., 14., 24., 16.,  7.,
        26., 15., 15., 21., 22., 16., 34., 16., 18., 33., 18., 18.,  4.,
        30., 23., 23., 18., 35., 16., 22., 26., 25., 25.,  8., 20., 20.,
        24., 19., 25., 18., 21., 27., 24., 28., 26., 23., 18., 23., 27.,
        26., 16., 13., 12., 22., 19., 31., 20., 24., 26., 29., 21., 21.,
        23., 24., 16., 13., 15., 30., 19., 28., 25., 32., 21., 36., 18.,
        30., 23., 26., 18., 26., 29., 15., 11., 26.]], dtype=float32)

In [55]:


y_test.as_matrix().astype(np.float32)



C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([24.8, 18.7, 16.1, 21. , 19.3, 13.4, 15. , 24.5, 16.8, 15.3, 20.3,
       13.4, 34.7, 18.7, 13.9, 17.1, 17.4, 21.8, 17.2, 20.7, 19.1, 22.2,
        5. , 15.4, 21.4, 17.4, 26.6, 24.5, 22. , 20.8, 21.5, 16.1, 20.9,
       19.5, 25. , 33.2,  7.2, 13.8, 20.1, 17.6, 10.9, 18.8, 28.7, 23.2,
       22.2, 14.9, 23.7, 28. ,  9.7, 23. , 50. , 13.8, 13.8, 26.7, 18.2,
       27.9, 32. ,  8.3, 18.9, 19.4, 11.5, 19.4, 20.4, 22. , 31.7, 21.2,
       19.7, 33.1, 26.4, 13.9, 21.1, 23.1, 26.6, 20.3,  8.7, 23.1, 10.8,
        7. , 25. , 17.3, 13.6, 17.7, 18.4, 13.1, 39.8, 20.1, 27.5, 50. ,
        7.2, 15. , 13.2, 33.1, 28.7, 30.3, 14.4, 43.1, 10.2, 21.2, 20.6,
       22.6, 21.7,  7.4, 13.1, 20. , 18.3, 21.2, 24.3, 19.8, 17.2, 22. ,
       23.4, 29.1, 23.8, 16.8, 13.4, 23.7, 20.9, 20.4, 13.1, 20.2, 10.4,
       22.4, 20.5, 24.5, 17.4, 18.5, 23.3, 23.5, 17. , 21.4, 21.7, 20.2,
       15.6, 15.7,  8.3, 29.8, 19.3, 26.2, 22.6, 34.9,  7. , 30.1,  9.6,
       31.2, 23.8, 21.9, 22.5, 23.9, 24.8, 15.6, 10

In [56]:


m.evaluate(x_test, y_test)



152/152 [==============================] - 0s 1ms/step


0.06881635322382576

In [37]:


scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)



In [38]:


m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")



In [57]:


m.fit(x_train_scaled, y_train, epochs=100, batch_size=10)



Epoch 1/100
354/354 [==============================] - 0s 311us/step - loss: 5.8913
Epoch 2/100
354/354 [==============================] - 0s 226us/step - loss: 2.5642
Epoch 3/100
354/354 [==============================] - 0s 198us/step - loss: 1.5775
Epoch 4/100
354/354 [==============================] - 0s 169us/step - loss: 1.1344
Epoch 5/100
354/354 [==============================] - 0s 226us/step - loss: 0.8729
Epoch 6/100
354/354 [==============================] - 0s 169us/step - loss: 0.6969
Epoch 7/100
354/354 [==============================] - 0s 198us/step - loss: 0.5729
Epoch 8/100
354/354 [==============================] - 0s 226us/step - loss: 0.4802
Epoch 9/100
354/354 [==============================] - 0s 169us/step - loss: 0.4092
Epoch 10/100
354/354 [==============================] - 0s 198us/step - loss: 0.3543
Epoch 11/100
354/354 [==============================] - 0s 198us/step - loss: 0.3105
Epoch 12/100
354/354 [==============================] - 0s 198us/step - lo

354/354 [==============================] - 0s 169us/step - loss: 0.0424
Epoch 98/100
354/354 [==============================] - 0s 198us/step - loss: 0.0420
Epoch 99/100
354/354 [==============================] - 0s 141us/step - loss: 0.0416
Epoch 100/100
354/354 [==============================] - 0s 169us/step - loss: 0.0413


In [58]:
x_test_scaled = scaler.transform(x_test)
m.predict(x_test_scaled).round().T

array([[31., 18., 14., 21., 19., 13., 11., 19., 17., 23., 20., 13., 35.,
        14., 13., 19., 19., 17., 13., 24., 13., 19.,  8., 15., 16., 18.,
        33., 17., 27., 16., 21., 16., 26., 16., 16., 37., 11., 13., 20.,
        13., 14., 17., 30., 25., 24., 16., 27., 28., 14., 15., 39., 12.,
        15., 29., 19., 17., 30., 12., 23., 18., 16., 20., 16., 21., 31.,
        20., 24., 31., 25., 14., 21., 24., 27., 20., 12., 22., 14.,  7.,
        30., 19., 14., 16., 17., 14., 40., 14., 14., 36., 15., 20., 10.,
        30., 27., 37., 16., 36., 14., 26., 20., 22., 19., 11., 16., 16.,
        16., 15., 19., 22., 19., 26., 26., 35., 24., 25., 14., 16., 20.,
        22., 17., 14., 11., 26., 21., 28., 17., 20., 25., 28., 24., 23.,
        25., 17., 18., 18., 13., 28., 21., 23., 29., 32., 16., 32., 14.,
        25., 25., 27., 18., 27., 23., 17., 12., 28.]], dtype=float32)

In [59]:


y_test.as_matrix().astype(np.float32)



C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([24.8, 18.7, 16.1, 21. , 19.3, 13.4, 15. , 24.5, 16.8, 15.3, 20.3,
       13.4, 34.7, 18.7, 13.9, 17.1, 17.4, 21.8, 17.2, 20.7, 19.1, 22.2,
        5. , 15.4, 21.4, 17.4, 26.6, 24.5, 22. , 20.8, 21.5, 16.1, 20.9,
       19.5, 25. , 33.2,  7.2, 13.8, 20.1, 17.6, 10.9, 18.8, 28.7, 23.2,
       22.2, 14.9, 23.7, 28. ,  9.7, 23. , 50. , 13.8, 13.8, 26.7, 18.2,
       27.9, 32. ,  8.3, 18.9, 19.4, 11.5, 19.4, 20.4, 22. , 31.7, 21.2,
       19.7, 33.1, 26.4, 13.9, 21.1, 23.1, 26.6, 20.3,  8.7, 23.1, 10.8,
        7. , 25. , 17.3, 13.6, 17.7, 18.4, 13.1, 39.8, 20.1, 27.5, 50. ,
        7.2, 15. , 13.2, 33.1, 28.7, 30.3, 14.4, 43.1, 10.2, 21.2, 20.6,
       22.6, 21.7,  7.4, 13.1, 20. , 18.3, 21.2, 24.3, 19.8, 17.2, 22. ,
       23.4, 29.1, 23.8, 16.8, 13.4, 23.7, 20.9, 20.4, 13.1, 20.2, 10.4,
       22.4, 20.5, 24.5, 17.4, 18.5, 23.3, 23.5, 17. , 21.4, 21.7, 20.2,
       15.6, 15.7,  8.3, 29.8, 19.3, 26.2, 22.6, 34.9,  7. , 30.1,  9.6,
       31.2, 23.8, 21.9, 22.5, 23.9, 24.8, 15.6, 10

In [60]:
m.evaluate(x_test_scaled, y_test)

152/152 [==============================] - 0s 66us/step


0.04481237793439313

In [44]:
pca = dec.PCA(n_components=13, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0    1.392515 -1.414743 -0.101660 -0.126167  0.308211  0.662036 -1.078846   
1   -0.453191 -0.100698 -0.089365 -0.632418  0.115651  1.078104 -1.531387   
2    1.395931 -1.401558 -0.230626 -0.352590 -0.429168 -0.432216 -0.725908   
3   -1.210819  0.349217 -0.617643  0.803447  0.315714 -1.106328 -0.508760   
4   -0.080339 -0.307171  0.026021  1.101466 -0.394107  0.621605  0.666964   
5    1.398296 -1.414749 -0.266506 -0.404331  2.565216  0.825079 -0.586051   
6   -0.688746 -0.059293  1.122622 -0.977928  0.043478 -0.011667 -0.186677   
7    1.626751 -1.574050  0.305474  0.382014 -1.989601  0.951702  3.859384   
8    0.192155  1.537002 -0.884819 -0.514621 -0.715615 -0.346599  2.327896   
9    0.044407 -0.439183  0.003075  0.885994 -0.638872 -0.651136 -0.310476   
10  -0.655730  0.006581  0.223745  1.789685  0.039233 -0.652710 -0.258851   
11  -0.753756 -0.014045  0.769918  0.731400  0.115987 -0.051187 -0.061845   
12  -0.737042  0.062178  0.416365  0.140543  0.047421 -0.192147 -0.197270   
13   0.106012 -0.540869 -0.555101 -0.013254 -0.667664 -0.517171  0.224018   
14  -0.730220 -0.000655  0.612535 -0.396838 -0.092265 -0.603903 -0.094739   
15  -0.566516 -0.096941 -1.422727 -0.931946  0.146392  0.868343 -1.103020   
16  -1.059868  0.221689 -0.321367  1.169283  0.191701 -1.233269 -0.395587   
17   0.015035  0.040900 -0.993389 -0.567745  0.018312  2.883718  0.457784   
18   1.497633 -0.545180  0.102844  0.148823  4.791093  0.756234  0.410120   
19   1.395866 -1.413971 -0.165060 -0.240669  2.300938  0.404390 -0.352747   
20  -0.571908 -0.042107  0.385088  1.010272  0.201546  1.318580 -0.500397   
21  -0.112419 -0.396050  1.416869 -0.317821 -0.415187 -0.336041 -0.004835   
22  -0.493330 -0.177059  1.336538  1.718892  0.061133  0.022833 -0.084685   
23   1.963563  3.389473  0.257280  0.185555 -1.483705 -0.319478 -0.497105   
24  -1.219915  0.405413 -1.120181  0.137350  0.299450  1.795816  2.662048   
25   1.386840 -1.365224  0.387433  0.668198 -0.660431 -0.294905 -0.534697   
26  -1.097586  0.277377  0.325347  0.641730  0.326856 -0.673378 -0.381150   
27  -0.429948  0.062861 -0.280997 -0.978716 -0.205745 -0.510351 -0.779506   
28  -0.516077  0.345113 -1.275936 -0.707710  0.195135  1.406034 -1.295874   
29  -0.702860  0.494349 -0.436119  0.745541 -0.099263 -0.826899 -0.326913   
..        ...       ...       ...       ...       ...       ...       ...   
324 -0.757267  0.041086 -1.251846 -0.515543 -0.276741 -0.781799  1.196236   
325 -0.733363 -0.008299 -0.161637 -0.817979 -0.073810 -0.685685 -0.281228   
326 -0.940153  0.151186 -0.207779 -0.413499  0.177019 -0.134466 -0.415888   
327 -0.715233 -0.036414  0.284576  1.953082  0.144242 -0.191477  0.159873   
328 -0.129147 -0.419538 -0.280431  0.621449 -0.298920  0.273634 -0.098503   
329 -0.097226 -0.183276  1.907805  0.476473 -0.398156 -0.248313  0.196619   
330  1.992750  3.583881  0.026337 -0.210591 -0.727037 -0.393200 -0.340685   
331  1.970345  3.435130  0.399480  0.389513  3.173949 -1.467121  1.708121   
332  1.948583  3.363297  0.865560  1.191605 -0.209127 -0.298678  0.245746   
333 -0.617824 -0.018726  0.853400  2.836643  0.058936  0.340786  1.091935   
334 -0.822816  0.096239 -0.159095 -0.340937  0.252941 -0.183301 -0.705184   
335  1.425175 -1.143851 -0.187892 -0.321188 -0.971417 -2.662200  0.512267   
336 -0.731995  0.029004 -1.330004 -0.652376  0.095673  0.752989 -0.455177   
337  0.139721 -0.594806 -0.983557 -0.661859 -0.748495  0.884076  2.003715   
338  1.422949 -1.170403 -0.165535 -0.258324  0.031948 -0.308061 -0.607836   
339  0.022646  0.106179 -0.999351 -0.596399 -0.144909  1.685397  1.127225   
340 -0.728820 -0.029165  0.409205  0.128309  0.203628 -0.069007 -0.898835   
341  1.920874  3.054046  0.429143  0.498309 -0.096519  0.592905 -0.533317   
342  1.937960  3.117986 -0.017900 -0.245899 -0.328363  0.488284 -0.797724   
343 -0.809150  0.195638 -0.249363 -0.505748  0.095424 -0.808377 -0.445993   
344 -

In [64]:


m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=13, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_logarithmic_error", optimizer="adam")



In [65]:


m.fit(x_train_white, y_train, epochs=100, batch_size=10)



Epoch 1/100
354/354 [==============================] - 0s 876us/step - loss: 7.9428
Epoch 2/100
354/354 [==============================] - 0s 198us/step - loss: 5.2934
Epoch 3/100
354/354 [==============================] - 0s 198us/step - loss: 4.0106
Epoch 4/100
354/354 [==============================] - 0s 198us/step - loss: 3.2021
Epoch 5/100
354/354 [==============================] - 0s 226us/step - loss: 2.6168
Epoch 6/100
354/354 [==============================] - 0s 198us/step - loss: 2.1632
Epoch 7/100
354/354 [==============================] - 0s 198us/step - loss: 1.8064
Epoch 8/100
354/354 [==============================] - 0s 169us/step - loss: 1.5184
Epoch 9/100
354/354 [==============================] - 0s 254us/step - loss: 1.2847
Epoch 10/100
354/354 [==============================] - 0s 254us/step - loss: 1.0926
Epoch 11/100
354/354 [==============================] - 0s 169us/step - loss: 0.9339
Epoch 12/100
354/354 [==============================] - 0s 226us/step - lo

354/354 [==============================] - 0s 198us/step - loss: 0.0204
Epoch 98/100
354/354 [==============================] - 0s 141us/step - loss: 0.0203
Epoch 99/100
354/354 [==============================] - 0s 169us/step - loss: 0.0202
Epoch 100/100
354/354 [==============================] - 0s 113us/step - loss: 0.0201


In [66]:


x_test_white = scaler.transform(x_test)
m.predict(x_test_white).round().T



array([[21., 21., 34., 15., 20., 20., 24., 21., 20., 40., 33., 33., 20.,
        23., 26., 21., 34., 24., 26., 34., 14., 19., 16., 11., 13., 29.,
        25., 22., 18., 18., 22., 26., 29., 22., 12., 18., 25., 23., 20.,
        26., 11., 23., 24., 25., 23., 13., 26., 21., 19., 15., 13., 27.,
        30., 26., 20., 17., 20., 29., 25., 19., 17., 31., 26., 28., 15.,
        21., 27., 28., 30., 11., 27., 22., 21., 29., 27., 29., 16., 25.,
        25., 33., 23., 12., 25., 23., 16., 16., 17., 28., 11., 21., 25.,
        20., 23., 24., 31., 18., 12., 28., 26., 29., 20., 18., 11., 12.,
        22., 15., 23., 26., 26., 21., 29., 26., 21., 23., 28., 13., 27.,
        24., 40., 30., 23., 19., 33., 22., 24., 24., 22., 25., 33., 33.,
        33., 11., 33., 35., 15., 23., 28., 21., 23., 17., 33., 22., 24.,
        18., 19., 28., 27., 32., 24., 28., 19., 20.]], dtype=float32)

In [67]:


y_test.as_matrix().astype(np.float32)



C:\Users\gerardh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([24.8, 18.7, 16.1, 21. , 19.3, 13.4, 15. , 24.5, 16.8, 15.3, 20.3,
       13.4, 34.7, 18.7, 13.9, 17.1, 17.4, 21.8, 17.2, 20.7, 19.1, 22.2,
        5. , 15.4, 21.4, 17.4, 26.6, 24.5, 22. , 20.8, 21.5, 16.1, 20.9,
       19.5, 25. , 33.2,  7.2, 13.8, 20.1, 17.6, 10.9, 18.8, 28.7, 23.2,
       22.2, 14.9, 23.7, 28. ,  9.7, 23. , 50. , 13.8, 13.8, 26.7, 18.2,
       27.9, 32. ,  8.3, 18.9, 19.4, 11.5, 19.4, 20.4, 22. , 31.7, 21.2,
       19.7, 33.1, 26.4, 13.9, 21.1, 23.1, 26.6, 20.3,  8.7, 23.1, 10.8,
        7. , 25. , 17.3, 13.6, 17.7, 18.4, 13.1, 39.8, 20.1, 27.5, 50. ,
        7.2, 15. , 13.2, 33.1, 28.7, 30.3, 14.4, 43.1, 10.2, 21.2, 20.6,
       22.6, 21.7,  7.4, 13.1, 20. , 18.3, 21.2, 24.3, 19.8, 17.2, 22. ,
       23.4, 29.1, 23.8, 16.8, 13.4, 23.7, 20.9, 20.4, 13.1, 20.2, 10.4,
       22.4, 20.5, 24.5, 17.4, 18.5, 23.3, 23.5, 17. , 21.4, 21.7, 20.2,
       15.6, 15.7,  8.3, 29.8, 19.3, 26.2, 22.6, 34.9,  7. , 30.1,  9.6,
       31.2, 23.8, 21.9, 22.5, 23.9, 24.8, 15.6, 10

In [68]:


m.evaluate(x_test_white, y_test)



152/152 [==============================] - 0s 1ms/step


0.23299342550729452